// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnlwkwfjqjffdgjcvecs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRubHdrd2ZqcWpmZmRnamN2ZWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODIzNjAsImV4cCI6MjA2MDA1ODM2MH0.yeEJwunmE0hkEy7M7IUU-2ln6-e8x2tZkKrtDxT-Q-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);